version: '3'
services: 
    tshock:
        image: zero23ku/tshock-terraria:1.0
        environment: 
            - PORT=7777
            - WORLD=default.wld 
            - AUTOCREATE=3
            - MAXPLAYERS=16
        ports:
            - "9000:7777" #HOST:CONTAINER. CONTAINER PORT MUST MATCH PORT SETTED IN ENVIROMENT
            - "7878:7878"
        volumes:
            - ./worlds:/opt/Terraria/world
            - ./config:/tshock/tshock
            - ./plugins:/tshock/ServerPlugins
